[tool.poetry]
name = "decaf_e_dev"
version = "0.1.1"
description = "A toolset for protein dynamics prediction and analysis"
authors = [
    "Gabriel Monteiro da Silva <gabriel.monteiro233@gmail.com>",
]
readme = "README.md"
license = "MIT, but separate licenses for the trained weights"
repository = "https://github.com/GMdSilva/decaf_e_dev"
classifiers = [
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
absl-py = "^1.0.0"
jax = { version = "^0.4.20", optional = true }
matplotlib = "^3.2.2"
tensorflow-macos = { version = "<2.14.0", markers = "sys_platform == 'darwin'" }
tensorflow-cpu = { version = "^2.12.1", markers = "sys_platform != 'darwin'" }
biopython = "<1.83"
numpy = "^1.22.0"
pandas = "^1.3.4"
alphafold-colabfold = { version = "v2.3.6", optional = true }
#alphafold-colabfold = { path = "../alphafold", develop = true, optional = true }
requests = "^2.26.0"
tqdm = "^4.62.2"
appdirs = "^1.4.4"
py3Dmol = "^2.0.1"
dm-haiku = "^0.0.12"
pyqtgraph = "*"
PyQt5 = "*"
importlib-metadata = "^4.8.2"

[tool.poetry.dev-dependencies]
# The latest version conflicts with tensorflow over typing-extensions
black = "^23.1.0"
jupyter = "^1.0.0"
pytest = "^6.2.5"

[tool.poetry.extras]
decaf_e_dev = ["decaf_e_dev"]

[tool.pytest.ini_options]
addopts = "--tb=short"

[tool.poetry.scripts]
decaf_init = 'decaf_e_dev.decaf_init:main'
mmseqs2_msa = 'decaf_e_dev.mmseqs2_msa:main'
jackhmmer_msa = 'decaf_e_dev.jackhmmer_msa:main'
predict_ensemble = 'decaf_e_dev.predict_ensemble:main'
rmsd_mode1d = 'decaf_e_dev.rmsd_mode1d:main'
rmsd_mode2d = 'decaf_e_dev.rmsd_mode2d:main'
tmscore_mode2d = 'decaf_e_dev.tmscore_mode2d:main'
tmscore_mode1d = 'decaf_e_dev.tmscore_mode1d:main'
pca_clustering = 'decaf_e_dev.pca_clustering:main'
rmsf_plddt = 'decaf_e_dev.rmsf_plddt:main'
save_traj = 'decaf_e_dev.save_traj:main'
run_gui = "decaf_e_dev.gui.run_gui:main"

[tool.black]
# Format only the new package, don't touch the existing stuff
include = '''
/(
  | decaf_e_dev
)/
'''
# The colabfold.py exclude doesn't work, but the "fmt: off" inside of it does
extend-exclude = '''
/(
  | __pycache__
  | decaf_e_dev/decaf_e_dev.py
)/
'''

[build-system]
requires = ["poetry-core>=1.0.0,<2.0.0"]
build-backend = "poetry.core.masonry.api"